### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by emedvedev**
A bunch of units, some minor changes to controllers (mostly for code reuse in tests) and sample ssh keys and ssl certificates for testing purposes.

### CODE REVIEW

**Comment by jfryman** [comment]
Tests need to check whether:

* SSL key was generated if one was not provided by a user, and its validity.
* SSH key was generated if one was not provided by a user, and its validity.

I am also confused with the SSH key here. In the installer, the public key is presented as the raw key, without the key type (`ssh-rsa`) and comment (usually the email). Yet, the accepted upload is a key that has these fields. The latter is the correct behavior, so the former should come in line and the copy-paste/download should also have key type and a comment.

Also, need a matrix to ensure that the YAML file gets written properly without failure depending on the user input. We're not doing any input validation ATM, but we should at least ensure that the happy path payloads from the installer are doing the right thing and not bombing out the app, and we have a quick way to make sure that we don't fall into regressions.

Reject when:
* Password is blank
* username is blank
* hostname is blank
* reject when no SSL keys are provided
* reject when no SSH keys are provided

* Allow/Disallow sending anonymous usage reports
* Self-signed vs provided (see above)
* Self-created SSH vs generated (see above)
* Allow/Disallow ChatOps

**Comment by emedvedev** [comment]
@jfryman 
> SSL key was generated if one was not provided by a user, and its validity.
We don’t generate SSL keys in the installer. In fact, I thought `puppet` does that.
> SSH key was generated if one was not provided by a user, and its validity.
It’s `test_ssh_keypairs_are_generated_correctly`, we’re running it through our `compare` script to ensure validity. 

> I am also confused with the SSH key here. In the installer, the public key is presented as the raw key, without the key type (ssh-rsa) and comment (usually the email). Yet, the accepted upload is a key that has these fields. The latter is the correct behavior, so the former should come in line and the copy-paste/download should also have key type and a comment.
The reason public key is generated like that is that it's the way `puppet` accepts it for some reason. I'll add `ssh-rsa` in the UI though, good point. "Download" link already has it, so you download the full key.

> Self-signed vs provided (see above)
> Self-created SSH vs generated (see above)
> Allow/Disallow ChatOps
We check this in `test_root_post`, `test_root_post_with_files` and `test_root_post_no_chatops`. I'll add the rest.

**Comment by jfryman** [comment]
@emedvedev yeah, you're right. I removed my comments about SSL in my comment above. Puppet owns self-signed. The installer only owns if the user passes in one.

The rest: :+1:

**Comment by emedvedev** [comment]
> In the installer, the public key is presented as the raw key, without the key type (ssh-rsa) and comment (usually the email).

Fixed.

> reject when no SSH keys are provided

This is something that's already tested and has a front-end validation as well as back-end remedy: we just fall back to a generated keypair in this case.

> Password is blank
> username is blank
> hostname is blank
> Allow/Disallow sending anonymous usage reports

Done, added four more tests. 

Note for blanks: in case with blanks pecan yields an error, and it's the expected behavior: we have validation in the front-end and if there's a blank despite that, then that just means a user tried to shoot himself in the leg. Tests just assert that puppet hasn't been launched so that the system isn't screwed, and that's it. Fine with you?

Overall, ready to merge.

**Pull request merged**
