### PR TITLE
Enterprise modifications

### PR DESCRIPTION
**Pull request by emedvedev**
1. "StackStorm Enterprise" section in the first tab:
enterprise
Checkbox state is written to "st2enterprise::token": if checked, `get_enterprise_token` method is evaluated; if not, an empty string is passed.

2. Installation progress page rework: a bit more love to the links and some minor changes.
install

3. Lots of linting: python is linted with `flake8`, js is linted with `jshint`.

Change as necessary: I think the wording has to be adjusted on the progress page. Also, I tried to make a separate "after install" page and found the experience a bit strange, so I just reworked links and element order instead. I think what we have now is good.

I'm also not sure if I have to write an empty string to "st2enterprise::token" or just don't have that key in config at all.

Lastly, @jfryman asked me to put a message about evaluating enterprise on the last page if the user hasn't ticked the box in the beginning:

> If a user did not enter a license key, they should have a link to some enterprise comparison page.

I think it's better to provide this link right next to the checkbox (see the first screenshot) to help with the decision, because on the last page it doesn't make a lot of sense: St2 is already installed and deployed, so it's too late to reconsider, right? Even if somebody does reconsider, what do we offer? Re-running puppet? I'm unsure about that scenario, so, again, I've put the link and a small description next to the enterprise checkbox. We can extend it later if necessary.

@jfryman @DoriftoShoes please review. :)

### CODE REVIEW

**Comment by dzimine** [comment]
Doesn't look right to me, look here https://github.com/StackStorm/discussions/issues/99
1) we enable "Enterprise", not "enterprise evaluation". The diff is in what license key the user puts there, and managing evaluation subscription is outside of the product (emails, etc). So wording needs to be different. 
     * We still need a section where we say, "here put your enterprise keys if you already have it, or try eval version for 30 days, go here to get your keys".

2) if as an enterprise user I received the license token, where do I place it? I envisioned a string input filed activated when enterprise checkbox is enabled...

> I think it's better to provide this link right next to the checkbox (see the first screenshot) to help with the decision, because on the last page it doesn't make a lot of sense: St2 is already installed and deployed, so it's too late to reconsider, right?
agreed (and where did the notion that it needs to be on  "last page" come from?)

DZ.

**Comment by emedvedev** [comment]
@dzimine so we have a choice: "I have a key", "I don't have anything and want a trial", "I only want Community", and an input field for a key if "I have a key" is selected, right? I was under the impression that tokens are hard-coded for now (cc @DoriftoShoes), that's why there's only an evaluation check-box.

> * We still need a section where we say, "here put your enterprise keys if you already have it, or try eval version for 30 days, go here to get your keys".
> 2) if as an enterprise user I received the license token, where do I place it? I envisioned a string input filed activated when enterprise checkbox is enabled...

What's the difference between "enterprise keys" and "license token"? Is it the same thing? I'm slightly confused here.

> agreed (and where did the notion that it needs to be on "last page" come from?)

I might've misunderstood. I still got this right in the end, so common sense wins. :)

**Comment by jfryman** [comment]
@emedvedev enterprise keys and license tokens are one and the same for this purpose. interchangable.

Let's just call it an "entitlement key".

A user doesn't have the ability to automatically get a 30 day entitlement key. But, we need them to be able to input a value so we can go and do the needful. It is manual for the time being.

This still leaves a drop-off for users who might want to try, but have no clue where to get an entitlement key. A link to our website (idk where, a signup page?) might be the ticket there.

**Comment by dzimine** [comment]
> I was under the impression that tokens are hard-coded for now (cc@DoriftoShoes), that's why there's only an evaluation check-box.

the end-to-end flow assumes we run the same installer script. 
If it changes for tech reasons, it creates extra work in other places, we need to discuss.

and no, enlightenment code is provided (see discussion).

>  "I have a key", "I don't have anything and want a trial", "I only want Community", and an input field for a key if "I have a key" is selected, right? 
yes, about right. 
a) I am on this page of an installer. I got here because I requested an Enterprise license (eval, or real, doesn’t matter), received a ‘key’, and a link, and now at the page where I can use it.
b) I am on this page because I just got the community and don’t care about enterprise. Move on with defaults.
c) like b) but now that I see “enterprise” I got curious, read the note about “getting evaluation key. Click the link, register, receive email with key (it happen to be eval key), paste it here, continue.

from UI, it’s just as you have it, except I’d put Enterprise checkpoint above the explanatory text.

Care to discuss details? Slack or call me tonight.

**Comment by emedvedev** [comment]
What if we simplify and only introduce an optional input with detailed instructions on how to request a trial? Like this. No checkboxes and radio buttons.
screenshot 2015-10-14 02 46 48

All your scenarios hold:
a. You have a key, enter it.
b. Don't enter anything, move on, we'll assume you want to install Community. I think it's implied from the wording that the key is not required (and the field is not marked as such), so it should be straightforward.
c. Click the link, register, paste, continue.

**Comment by dzimine** [comment]
Checkbox left of StackStorm enterprise will be a better UX. It's more inviting, and makes the choice and the input more explicit. Other than that, excellent.

**Comment by emedvedev** [comment]
Putting checkbox inside a header doesn't look very nice, but I do agree with the sentiment. How about this?

screenshot 2015-10-14 03 15 20

**Comment by dzimine** [comment]
LGTM. :+1:

**Comment by emedvedev** [comment]
@DoriftoShoes UI is good, wiring should be good as well, just need to confirm it passes the license key to puppet correctly.

**Pull request merged**
